### PR TITLE
fix: add mask SpriteTextInput - fix #29

### LINKED ISSUE #29: Fix SpriteTextInput masks
Normal text:

Image

Placeholder:

Image

### PR DESCRIPTION
**Pull request by diegogliarte**
placeholder

### CODE REVIEW

File: src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx [hunk 1]
```diff
@@ -382,32 +382,37 @@ export const SpriteTextInputComponent: FC<SpriteTextInputProps> = ({
         alpha={backgroundAlpha}
         tint={backgroundColor}
       />
-      <SpriteTextComponent
-        spriteSheet={spriteSheet}
-        text={placeholder}
+      <ContainerComponent
+        maskPolygon={[
+          padding?.left / 2,
```
Comment (diegogliarte) [inline src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx:387]: The /2 is done for UI/UX purposes, I'm pretty sure the default html input element does the same

Comment (pagoru) [reply src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx:387]: I don't really like it, and it's not being rounded, so it shows decimals. :/

Comment (diegogliarte) [reply src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx:387]: The problem without any similar approach is that then theres no cue of whether there's "more text" to the left if you overflow it.

If you still don't like it, just lmk and I'll remove it

Comment (pagoru) [reply src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx:387]: Same applies to the right with that logic, no? If you don't see "more text" to the right. This is an input, if you overflow to the left because of the width limit, you will see incomplete words or even incomplete chars to the left and you are currently writing, so it's really complicated to "forget" that you can go left.
