### PR TITLE
fix: input jumping to the end when value changes - fix #47

### LINKED ISSUE #47: when moving cursor on input and writing jumps to the end
Image

### PR DESCRIPTION
**Pull request by diegogliarte**
The bug only happened when we had something like this:

image
image
image

This made the component to rerender every time and reset the cursor to the current text length (the end). There's no need to update cursorIndexRef.current there since it's being already updated inside the update() / writeChar().

Also fixed the maxLength. If you passed X, it would only allow X - 1.

NOTES:

I've seen that the onPaste doesn't work when the cursor is in the middle, I can fix it but didn't know if it was on purpose.

### CODE REVIEW

File: src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx [hunk 1]
```diff
@@ -334,7 +334,6 @@ export const SpriteTextInputComponent: FC<SpriteTextInputProps> = ({
 
   useEffect(() => {
     textRef.current = value ?? textRef.current ?? "";
-    cursorIndexRef.current = textRef.current.length;
```
Comment (pagoru) [inline src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx:337]: This is intentional to know if value is changed outside and go to the end, so this change would provoke another bug when you change the values outside the component.

- We need to be able to change the value of the input and the cursor needs to go the end BUT:
- When it's only an update from the previous text, the cursor needs to remain at the same spot

Maybe checking the last text vs the new value, and if the variation between the value and the textRef is only a char, maintain the cursorIndexRef, if not, assign the current text length.

This needs a few tests to check that every race condition works

Comment (diegogliarte) [reply src/components/prefabs/sprite-text-input/sprite-text-input.component.tsx:337]: Kind of weird to change the user's input programatically, but I guess it might happen in some cases.

I did something similar to what you said, but using that onKeyDown is ALWAYS being done before the useEffect (because onKeyDown calls the onChange, which is what is changing 'value', triggering the useEffect). I added some components to test this new behaviour.

**Comment by diegogliarte** [comment]
> > I've seen that the onPaste doesn't work when the cursor is in the middle, I can fix it but didn't know if it was on purpose.
> 
> Not intentional, it's a bug, feel free to fix it! 👯

About this, what should the behaviour be when:

Max Length = 5
Current Input = "te|st" (cursor between 'e' and 's')
I have "world" on my clipboard
I paste

Should the result be "tewor"?

**Comment by pagoru** [comment]
> About this, what should the behaviour be when:
> 
> Max Length = 5 Current Input = "te|st" (cursor between 'e' and 's') I have "world" on my clipboard I paste
> 
> Should the result be "tewor"?

Nope, `teworld|st` with the cursor at the ends of the `world`

**Comment by diegogliarte** [comment]
> > About this, what should the behaviour be when:
> > Max Length = 5 Current Input = "te|st" (cursor between 'e' and 's') I have "world" on my clipboard I paste
> > Should the result be "tewor"?
> 
> Nope, `teworld|st` with the cursor at the end of the `world`

So it would ignore the maxLength?? Currently it's being done like this (adds to the end, cuts from the end)

`textRef.current = (textRef.current + text).substring(0, maxLength);`

**Comment by pagoru** [comment]
> So it would ignore the maxLength??

UPPPPSSSS, I didn't read the maxLength thing, you are totally correct, ignore what I wrote
